import type { PricingPlan, Testimonial, BlogPost, FAQItem } from '@/types';

export const APP_NAME = 'PixiVisual';
export const APP_TAGLINE = 'AI-Powered Visual Content Creation';
export const APP_DESCRIPTION = 'Create stunning visuals, social media creatives, marketing materials, brand assets, and AI-generated artwork.';

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'free',
    name: 'Free',
    price: { monthly: 0, yearly: 0 },
    description: 'Perfect for individuals just getting started with visual content.',
    features: [
      '5 AI generations per month',
      '10 design projects',
      'Basic templates (500+)',
      'Standard export (PNG, JPG)',
      '1GB cloud storage',
      'Community support',
    ],
  },
  {
    id: 'pro',
    name: 'Pro',
    price: { monthly: 19, yearly: 15 },
    description: 'For creators and professionals who need more power.',
    features: [
      '100 AI generations per month',
      'Unlimited design projects',
      'Premium templates (10,000+)',
      'All export formats',
      '20GB cloud storage',
      'Background removal',
      'Brand Kit (3 brands)',
      'Priority support',
    ],
    highlighted: true,
    badge: 'Most Popular',
  },
  {
    id: 'business',
    name: 'Business',
    price: { monthly: 49, yearly: 39 },
    description: 'For teams and businesses scaling their creative output.',
    features: [
      'Unlimited AI generations',
      'Unlimited projects',
      'All templates + custom upload',
      'All export formats + API',
      '100GB cloud storage',
      'Team collaboration (10 members)',
      'Unlimited Brand Kits',
      'Analytics dashboard',
      'Client review portal',
      'Dedicated support',
    ],
    badge: 'Best Value',
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: { monthly: 149, yearly: 119 },
    description: 'For large organizations with advanced creative needs.',
    features: [
      'Everything in Business',
      'Unlimited team members',
      'Custom AI model training',
      '1TB cloud storage',
      'SSO & advanced security',
      'White-label option',
      'Custom integrations',
      'SLA guarantee',
      'Dedicated account manager',
      '24/7 priority support',
    ],
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    role: 'Head of Marketing',
    company: 'TechFlow Inc.',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b5e5?w=80&h=80&fit=crop&crop=face',
    content: 'PixiVisual has completely transformed how we create marketing content. Our team produces 10x more designs in half the time. The AI generation is incredibly accurate.',
    rating: 5,
  },
  {
    id: '2',
    name: 'Marcus Williams',
    role: 'Creative Director',
    company: 'Bloom Agency',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face',
    content: "As a design agency, we needed a tool that keeps up with our clients' demands. PixiVisual's collaboration features and template library are absolutely world-class.",
    rating: 5,
  },
  {
    id: '3',
    name: 'Priya Sharma',
    role: 'Social Media Manager',
    company: 'GrowthLabs',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&crop=face',
    content: 'I manage 12 brand accounts and PixiVisual keeps all their brand kits organized. Creating platform-optimized content has never been easier.',
    rating: 5,
  },
  {
    id: '4',
    name: 'James Rodriguez',
    role: 'Founder & CEO',
    company: 'LaunchPad Brands',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&crop=face',
    content: "We went from spending $3,000/month on design freelancers to $49/month on PixiVisual Business. The quality is indistinguishable and our team loves it.",
    rating: 5,
  },
  {
    id: '5',
    name: 'Emma Thompson',
    role: 'Content Creator',
    company: 'Self-Employed',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=80&h=80&fit=crop&crop=face',
    content: 'The AI design studio is pure magic. I just describe what I need and it generates exactly that. My Instagram engagement has gone up 340% since switching.',
    rating: 5,
  },
  {
    id: '6',
    name: 'David Kim',
    role: 'E-commerce Director',
    company: 'StyleHouse',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=80&h=80&fit=crop&crop=face',
    content: 'Product mockups that used to take our team hours now take seconds. The batch creation feature for our product catalog saves us countless hours every week.',
    rating: 5,
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'The Complete Guide to AI-Powered Graphic Design in 2025',
    excerpt: 'Discover how AI is revolutionizing the design industry and how you can leverage these tools to create stunning visuals faster than ever.',
    content: '',
    author: 'Sarah Chen',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b5e5?w=40&h=40&fit=crop&crop=face',
    category: 'AI Design',
    tags: ['AI', 'Design', 'Tutorial', 'Productivity'],
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=450&fit=crop',
    publishedAt: '2025-06-15',
    readTime: 8,
  },
  {
    id: '2',
    title: '10 Social Media Design Trends Dominating 2025',
    excerpt: 'From bold typography to immersive 3D elements, these design trends are shaping how brands communicate on social media this year.',
    content: '',
    author: 'Marcus Williams',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&crop=face',
    category: 'Social Media',
    tags: ['Social Media', 'Trends', 'Design', 'Marketing'],
    image: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&h=450&fit=crop',
    publishedAt: '2025-06-10',
    readTime: 6,
  },
  {
    id: '3',
    title: 'How to Build a Consistent Brand Identity from Scratch',
    excerpt: 'A step-by-step guide to creating a cohesive brand identity that resonates with your target audience and stands out in a crowded market.',
    content: '',
    author: 'Priya Sharma',
    authorAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=40&h=40&fit=crop&crop=face',
    category: 'Branding',
    tags: ['Branding', 'Identity', 'Logo Design', 'Strategy'],
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=450&fit=crop',
    publishedAt: '2025-06-05',
    readTime: 10,
  },
  {
    id: '4',
    title: 'Mastering Color Psychology in Marketing Design',
    excerpt: 'Understanding how colors affect emotions and purchasing decisions can dramatically improve your marketing materials and conversion rates.',
    content: '',
    author: 'James Rodriguez',
    authorAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=40&h=40&fit=crop&crop=face',
    category: 'Marketing',
    tags: ['Color Theory', 'Psychology', 'Marketing', 'Design'],
    image: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&h=450&fit=crop',
    publishedAt: '2025-05-28',
    readTime: 7,
  },
  {
    id: '5',
    title: 'Video Content Strategy: From Static to Motion Graphics',
    excerpt: 'Video continues to dominate engagement metrics. Learn how to upgrade your content strategy with compelling motion graphics and short-form videos.',
    content: '',
    author: 'Emma Thompson',
    authorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=40&h=40&fit=crop&crop=face',
    category: 'Video',
    tags: ['Video', 'Motion Graphics', 'Content Strategy', 'Engagement'],
    image: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&h=450&fit=crop',
    publishedAt: '2025-05-20',
    readTime: 9,
  },
  {
    id: '6',
    title: 'Typography Fundamentals Every Designer Must Know',
    excerpt: 'Typography is the backbone of great design. Master these fundamental principles to elevate every project you create.',
    content: '',
    author: 'David Kim',
    authorAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=40&h=40&fit=crop&crop=face',
    category: 'Design Basics',
    tags: ['Typography', 'Design', 'Fundamentals', 'Fonts'],
    image: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=450&fit=crop',
    publishedAt: '2025-05-15',
    readTime: 5,
  },
];

export const FAQ_ITEMS: FAQItem[] = [
  {
    id: '1',
    question: 'What is PixiVisual and how does it work?',
    answer: "PixiVisual is an AI-powered visual content creation platform that helps you design social media posts, logos, banners, presentations, videos, and marketing materials. Simply describe what you want, choose from thousands of templates, and our AI helps you create stunning visuals in minutes.",
    category: 'General',
  },
  {
    id: '2',
    question: 'Do I need design experience to use PixiVisual?',
    answer: 'Not at all! PixiVisual is designed for everyone, from complete beginners to professional designers. Our intuitive drag-and-drop editor and AI assistance make it easy for anyone to create professional-quality visuals.',
    category: 'General',
  },
  {
    id: '3',
    question: 'How many AI generations do I get per month?',
    answer: 'Free users get 5 AI generations per month. Pro users get 100 generations, Business users get unlimited generations, and Enterprise users also get unlimited generations with priority processing.',
    category: 'Features',
  },
  {
    id: '4',
    question: 'Can I collaborate with my team?',
    answer: 'Yes! Business and Enterprise plans include full team collaboration features including real-time co-editing, comments, approval workflows, version history, and client review portals.',
    category: 'Features',
  },
  {
    id: '5',
    question: 'What file formats can I export?',
    answer: 'Free and Pro users can export PNG, JPG, and PDF. Business and Enterprise users additionally get SVG, MP4 (for animations), GIF, WebP, and API access for automated exports.',
    category: 'Features',
  },
  {
    id: '6',
    question: 'Can I cancel my subscription anytime?',
    answer: "Yes, you can cancel your subscription at any time. You'll continue to have access to your plan's features until the end of your current billing period, and then you'll be moved to the Free plan.",
    category: 'Billing',
  },
  {
    id: '7',
    question: 'Is there a free trial for paid plans?',
    answer: "Yes! We offer a 14-day free trial for Pro and Business plans with no credit card required. You'll get full access to all features during the trial period.",
    category: 'Billing',
  },
  {
    id: '8',
    question: 'Do you offer refunds?',
    answer: "We offer a 30-day money-back guarantee for all paid plans. If you're not satisfied with PixiVisual for any reason, contact our support team within 30 days of your purchase for a full refund.",
    category: 'Billing',
  },
  {
    id: '9',
    question: 'How secure is my data?',
    answer: 'Your data security is our highest priority. All data is encrypted in transit and at rest using AES-256 encryption. We are SOC 2 Type II certified and GDPR compliant. You retain full ownership of all your designs.',
    category: 'Security',
  },
  {
    id: '10',
    question: 'Can I use PixiVisual designs for commercial purposes?',
    answer: "Yes! All designs created with PixiVisual on any paid plan are fully licensed for commercial use. Free plan designs can be used commercially as long as they don't include premium stock assets.",
    category: 'Legal',
  },
  {
    id: '11',
    question: 'Does PixiVisual integrate with other tools?',
    answer: 'PixiVisual integrates with Slack, Google Drive, Dropbox, HubSpot, Mailchimp, Shopify, and many more platforms. Business and Enterprise plans also have access to our REST API.',
    category: 'Integrations',
  },
  {
    id: '12',
    question: 'What happens to my designs if I downgrade my plan?',
    answer: "Your designs are always safe! If you downgrade, you keep all your existing designs but lose access to premium features. Any designs using premium assets will still be viewable but may require upgrading to edit.",
    category: 'Billing',
  },
];

export const STATS = [
  { value: '10M+', label: 'Designs Created' },
  { value: '2M+', label: 'Active Users' },
  { value: '150+', label: 'Countries' },
  { value: '99.9%', label: 'Uptime' },
];

export const FEATURES_LIST = [
  {
    icon: 'Sparkles',
    title: 'AI Design Studio',
    description: 'Generate stunning visuals from simple text prompts. Our AI understands context, style, and branding to create perfect designs instantly.',
    color: 'purple',
  },
  {
    icon: 'PenTool',
    title: 'Professional Editor',
    description: 'Layer-based drag-and-drop editor with 100,000+ elements, fonts, and templates. Everything you need to bring your vision to life.',
    color: 'pink',
  },
  {
    icon: 'Palette',
    title: 'Brand Kit Management',
    description: 'Store and apply your brand colors, fonts, and logos consistently across all designs. Maintain perfect brand consistency effortlessly.',
    color: 'blue',
  },
  {
    icon: 'Users',
    title: 'Team Collaboration',
    description: 'Real-time co-editing, comments, approval workflows, and version history. Design together, no matter where your team is.',
    color: 'purple',
  },
  {
    icon: 'BarChart2',
    title: 'Performance Analytics',
    description: 'Track design performance, brand consistency scores, and content engagement. Make data-driven creative decisions.',
    color: 'pink',
  },
  {
    icon: 'Store',
    title: 'Template Marketplace',
    description: 'Browse, buy, and sell professional templates. Hire designers or showcase your portfolio to thousands of potential clients.',
    color: 'blue',
  },
];
